import type { Category, Place, TourGuideContact } from "./travel-types";
import { haversineKm } from "./travel-types";

export const WORLDWIDE_TOUR_GUIDES: Record<string, TourGuideContact> = {
  maldives: {
    name: "Mohamed Zameel",
    phone: "+960 302 2200",
    agency: "Maldives Ministry of Tourism Visitor & Marine Guides Desk",
    verified: true,
    language: "English, Dhivehi, Arabic",
  },
  paris: {
    name: "Camille Laurent",
    phone: "+33 1 49 52 42 63",
    agency: "Paris Convention & Visitors Bureau Certified Guides",
    verified: true,
    language: "English, French, Spanish",
  },
  london: {
    name: "Arthur Pendelton",
    phone: "+44 20 7578 1000",
    agency: "VisitBritain Blue Badge Tourist Information Desk",
    verified: true,
    language: "English, German, French",
  },
  dubai: {
    name: "Rashid Al Falasi",
    phone: "+971 600 555559",
    agency: "Dubai Department of Economy and Tourism (DET) Certified Desk",
    verified: true,
    language: "English, Arabic, Hindi",
  },
  tokyo: {
    name: "Kenji Sato",
    phone: "+81 3 3201 3331",
    agency: "JNTO Tokyo Tourist Information Center Registered Guides",
    verified: true,
    language: "English, Japanese",
  },
  rome: {
    name: "Marco Bellini",
    phone: "+39 06 0608",
    agency: "Comune di Roma Official Tourist Information Guides",
    verified: true,
    language: "English, Italian, Spanish",
  },
  newyork: {
    name: "Sarah Jenkins",
    phone: "+1 212 484 1222",
    agency: "NYC Tourism & Conventions Licensed Guides Association",
    verified: true,
    language: "English, Spanish",
  },
  bali: {
    name: "Wayan Sudarta",
    phone: "+62 361 235600",
    agency: "Bali Tourism Board & Certified Cultural Guides",
    verified: true,
    language: "English, Indonesian",
  },
  kodaikanal: {
    name: "P. Muthuvel",
    phone: "+91 4542 241675",
    agency: "TTDC Kodaikanal Tourism Information Counter",
    verified: true,
    language: "English, Tamil, Hindi",
  },
  bihar: {
    name: "Alok Kumar Sinha",
    phone: "+91 612 2506048",
    agency: "Bihar State Tourism Development Corporation (BSTDC) Heritage Desk",
    verified: true,
    language: "English, Hindi, Bhojpuri, Maithili",
  },
  madurai: {
    name: "K. Sundaram",
    phone: "+91 452 233 4757",
    agency: "Tamil Nadu Tourism Dev Corp (TTDC) Temple City Desk",
    verified: true,
    language: "English, Tamil, Hindi",
  },
  chennai: {
    name: "R. Natarajan",
    phone: "+91 44 2538 3333",
    agency: "TTDC Head Office Certified Heritage Tour Guides",
    verified: true,
    language: "English, Tamil, Telugu, Hindi",
  },
  general: {
    name: "Global Tourist Concierge",
    phone: "+1 800 555 0199",
    agency: "International Traveler Support & Verified Guide Registry",
    verified: true,
    language: "Multilingual",
  },
};

export const VERIFIED_WORLD_PLACES: Record<string, Place[]> = {
  maldives: [
    {
      id: "mv_hulhumale_beach",
      name: "Hulhumalé White Sand Lagoon Beach",
      category: "Beach",
      lat: 4.215,
      lon: 73.541,
      address: "Hulhumalé Island, Kaafu Atoll, Maldives",
      rating: 4.8,
      ratingCount: 14200,
      price: "Free",
      hoursText: ["Open 24 hours"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hulhumale+Beach+Maldives",
      distanceKm: 2.5,
      photoUrl:
        "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Hulhumale+Beach+Maldives",
      phone: "+960 302 2200",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_grand_mosque",
      name: "Grand Friday Mosque & Islamic Centre",
      category: "Temples",
      lat: 4.1779,
      lon: 73.5132,
      address: "Medhuziyaraiy Magu, Malé 20115, Maldives",
      rating: 4.7,
      ratingCount: 8900,
      price: "Free",
      hoursText: ["09:00 - 17:00 (Outside prayer times)"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1020 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Grand+Friday+Mosque+Male",
      distanceKm: 0.8,
      photoUrl:
        "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Grand+Friday+Mosque+Male",
      phone: "+960 332 3843",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_kurumba_resort",
      name: "Kurumba Luxury Coral Beach Resort",
      category: "Hotels",
      lat: 4.228,
      lon: 73.519,
      address: "Vihamanaafushi, North Malé Atoll, Maldives",
      rating: 4.9,
      ratingCount: 6800,
      price: "$380",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kurumba+Maldives",
      distanceKm: 4.1,
      photoUrl:
        "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Kurumba+Maldives",
      phone: "+960 664 2324",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_male_national_museum",
      name: "National Museum & Sultan Park",
      category: "Culture",
      lat: 4.1755,
      lon: 73.5108,
      address: "Chaandhanee Magu, Malé, Maldives",
      rating: 4.5,
      ratingCount: 4200,
      price: "$10",
      hoursText: ["10:00 - 16:00 (Closed Fridays)"],
      periods: [0, 1, 2, 3, 4, 6].map((day) => ({ day, open: 600, close: 960 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=National+Museum+Male",
      distanceKm: 0.6,
      photoUrl:
        "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/National+Museum+Male",
      phone: "+960 332 2254",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_male_local_market",
      name: "Malé Fish & Local Bazaar",
      category: "Shopping",
      lat: 4.179,
      lon: 73.509,
      address: "Boduthakurufaanu Magu, Malé, Maldives",
      rating: 4.4,
      ratingCount: 5100,
      price: "Free",
      hoursText: ["06:00 - 20:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 360, close: 1200 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Male+Local+Market",
      distanceKm: 0.9,
      photoUrl:
        "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Male+Local+Market",
      phone: "+960 302 2200",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_maafushi_island",
      name: "Maafushi Coral Island Adventure",
      category: "Amusement",
      lat: 3.94,
      lon: 73.49,
      address: "South Malé Atoll, Maldives",
      rating: 4.8,
      ratingCount: 16000,
      price: "$45",
      hoursText: ["08:00 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 480, close: 1080 })),
      wheelchair: false,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Maafushi+Island+Maldives",
      distanceKm: 22.0,
      photoUrl:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Maafushi+Maldives",
      phone: "+960 302 2200",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
    {
      id: "mv_bodu_fort",
      name: "Bodu Thakurufaanu Historical Citadel",
      category: "Fort",
      lat: 4.176,
      lon: 73.512,
      address: "Henveiru, Malé, Maldives",
      rating: 4.5,
      ratingCount: 3100,
      price: "Free",
      hoursText: ["09:00 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1080 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Bodu+Thakurufaanu+Citadel+Male",
      distanceKm: 0.7,
      photoUrl:
        "https://images.unsplash.com/photo-1590073844006-33379778ae09?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Male+Maldives",
      phone: "+960 302 2200",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["maldives"],
    },
  ],

  paris: [
    {
      id: "fr_eiffel_tower",
      name: "Eiffel Tower (Tour Eiffel)",
      category: "Heritage",
      lat: 48.8584,
      lon: 2.2945,
      address: "Champ de Mars, 5 Av. Anatole France, 75007 Paris, France",
      rating: 4.7,
      ratingCount: 340000,
      price: "€29.40",
      hoursText: ["09:30 - 23:45"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 570, close: 1425 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Eiffel+Tower+Paris",
      distanceKm: 3.2,
      photoUrl:
        "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Eiffel+Tower+Paris",
      phone: "+33 892 70 12 39",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_louvre_museum",
      name: "Louvre Museum & Glass Pyramid",
      category: "Culture",
      lat: 48.8606,
      lon: 2.3376,
      address: "Rue de Rivoli, 75001 Paris, France",
      rating: 4.7,
      ratingCount: 280000,
      price: "€22",
      hoursText: ["09:00 - 18:00 (Closed Tuesdays)"],
      periods: [0, 1, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1080 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Louvre+Museum+Paris",
      distanceKm: 1.1,
      photoUrl:
        "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Louvre+Museum+Paris",
      phone: "+33 1 40 20 53 17",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_conciergerie_fort",
      name: "Conciergerie Royal Fortress & Prison",
      category: "Fort",
      lat: 48.856,
      lon: 2.3458,
      address: "2 Bd du Palais, 75001 Paris, France",
      rating: 4.6,
      ratingCount: 38000,
      price: "€13",
      hoursText: ["09:30 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 570, close: 1080 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Conciergerie+Paris",
      distanceKm: 0.5,
      photoUrl:
        "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Conciergerie+Paris",
      phone: "+33 1 53 40 60 80",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_notre_dame",
      name: "Notre-Dame Cathedral & Sainte-Chapelle",
      category: "Temples",
      lat: 48.853,
      lon: 2.3499,
      address: "6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris, France",
      rating: 4.8,
      ratingCount: 190000,
      price: "Free / €11.50 for Chapelle",
      hoursText: ["08:00 - 18:45"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 480, close: 1125 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Notre+Dame+Paris",
      distanceKm: 0.6,
      photoUrl:
        "https://images.unsplash.com/photo-1478358161113-b0e11994a36b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Notre+Dame+Cathedral+Paris",
      phone: "+33 1 42 34 56 10",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_champs_elysees",
      name: "Champs-Élysées & Galeries Lafayette",
      category: "Shopping",
      lat: 48.8698,
      lon: 2.3075,
      address: "Av. des Champs-Élysées, 75008 Paris, France",
      rating: 4.6,
      ratingCount: 88000,
      price: "Free",
      hoursText: ["10:00 - 20:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1230 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Champs+Elysees+Paris",
      distanceKm: 2.8,
      photoUrl:
        "https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Champs+Elysees+Paris",
      phone: "+33 1 42 66 55 55",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_ritz_hotel",
      name: "The Ritz Paris Luxury Grand Hotel",
      category: "Hotels",
      lat: 48.868,
      lon: 2.329,
      address: "15 Place Vendôme, 75001 Paris, France",
      rating: 4.9,
      ratingCount: 14000,
      price: "€1200",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Ritz+Paris",
      distanceKm: 1.4,
      photoUrl:
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Ritz+Paris",
      phone: "+33 1 43 16 30 30",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_disneyland_paris",
      name: "Disneyland Paris Theme Park",
      category: "Amusement",
      lat: 48.8722,
      lon: 2.7758,
      address: "Bd de Parc, 77700 Coupvray, France",
      rating: 4.7,
      ratingCount: 180000,
      price: "€62",
      hoursText: ["09:30 - 22:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 570, close: 1320 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Disneyland+Paris",
      distanceKm: 32.0,
      photoUrl:
        "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Disneyland+Paris",
      phone: "+33 825 30 05 00",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
    {
      id: "fr_paris_plages",
      name: "Paris Plages Seine Promenade Beach",
      category: "Beach",
      lat: 48.854,
      lon: 2.355,
      address: "Voie Georges Pompidou, 75004 Paris, France",
      rating: 4.5,
      ratingCount: 12000,
      price: "Free",
      hoursText: ["09:00 - 23:00 (Summer season)"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1380 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Paris+Plages",
      distanceKm: 0.9,
      photoUrl:
        "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Paris+Plages",
      phone: "+33 1 49 52 42 63",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["paris"],
    },
  ],

  london: [
    {
      id: "uk_tower_of_london",
      name: "Tower of London Historic Royal Fortress",
      category: "Fort",
      lat: 51.5081,
      lon: -0.0759,
      address: "London EC3N 4AB, United Kingdom",
      rating: 4.7,
      ratingCount: 125000,
      price: "£33.60",
      hoursText: ["09:00 - 17:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1050 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tower+of+London",
      distanceKm: 3.5,
      photoUrl:
        "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Tower+of+London",
      phone: "+44 333 320 6000",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_big_ben",
      name: "Big Ben & Palace of Westminster",
      category: "Heritage",
      lat: 51.5007,
      lon: -0.1246,
      address: "London SW1A 0AA, United Kingdom",
      rating: 4.8,
      ratingCount: 180000,
      price: "Free view / £30 interior tour",
      hoursText: ["09:00 - 17:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1020 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Big+Ben+London",
      distanceKm: 1.2,
      photoUrl:
        "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Big+Ben+London",
      phone: "+44 20 7219 4114",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_british_museum",
      name: "The British Museum",
      category: "Culture",
      lat: 51.5194,
      lon: -0.127,
      address: "Great Russell St, London WC1B 3DG, United Kingdom",
      rating: 4.7,
      ratingCount: 160000,
      price: "Free",
      hoursText: ["10:00 - 17:00 (Fridays open until 20:30)"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1020 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=British+Museum+London",
      distanceKm: 1.8,
      photoUrl:
        "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/British+Museum+London",
      phone: "+44 20 7323 8000",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_westminster_abbey",
      name: "Westminster Abbey Royal Coronation Church",
      category: "Temples",
      lat: 51.4993,
      lon: -0.1273,
      address: "Dean's Yard, London SW1P 3PA, United Kingdom",
      rating: 4.7,
      ratingCount: 65000,
      price: "£27",
      hoursText: ["09:30 - 15:30"],
      periods: [0, 1, 2, 3, 4, 5].map((day) => ({ day, open: 570, close: 930 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Westminster+Abbey+London",
      distanceKm: 1.3,
      photoUrl:
        "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Westminster+Abbey+London",
      phone: "+44 20 7222 5152",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_harrods_shopping",
      name: "Harrods World Luxury Department Store",
      category: "Shopping",
      lat: 51.4994,
      lon: -0.1632,
      address: "87-135 Brompton Rd, Knightsbridge, London SW1X 7XL",
      rating: 4.6,
      ratingCount: 78000,
      price: "Free entry",
      hoursText: ["10:00 - 21:00 (Sundays 11:30 - 18:00)"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1260 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Harrods+London",
      distanceKm: 3.1,
      photoUrl:
        "https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Harrods+London",
      phone: "+44 20 7730 1234",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_the_savoy",
      name: "The Savoy Landmark Luxury Hotel",
      category: "Hotels",
      lat: 51.5103,
      lon: -0.1205,
      address: "Strand, London WC2R 0EZ, United Kingdom",
      rating: 4.8,
      ratingCount: 12000,
      price: "£650",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Savoy+London",
      distanceKm: 0.8,
      photoUrl:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/The+Savoy+London",
      phone: "+44 20 7836 4343",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
    {
      id: "uk_london_eye",
      name: "The London Eye Giant Observation Wheel",
      category: "Amusement",
      lat: 51.5033,
      lon: -0.1195,
      address: "Riverside Building, County Hall, London SE1 7PB",
      rating: 4.6,
      ratingCount: 155000,
      price: "£29",
      hoursText: ["10:00 - 20:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1230 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=London+Eye",
      distanceKm: 1.1,
      photoUrl:
        "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/London+Eye",
      phone: "+44 20 7967 8000",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["london"],
    },
  ],

  dubai: [
    {
      id: "ae_burj_khalifa",
      name: "Burj Khalifa At The Top Observatory",
      category: "Heritage",
      lat: 25.1972,
      lon: 55.2744,
      address: "1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai, UAE",
      rating: 4.8,
      ratingCount: 240000,
      price: "AED 179",
      hoursText: ["08:30 - 23:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 510, close: 1380 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Burj+Khalifa+Dubai",
      distanceKm: 1.5,
      photoUrl:
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Burj+Khalifa+Dubai",
      phone: "+971 4 888 8888",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_al_fahidi_fort",
      name: "Al Fahidi Historical Fort & Bastakiya",
      category: "Fort",
      lat: 25.2635,
      lon: 55.2972,
      address: "Al Fahidi St, Bur Dubai, Dubai, UAE",
      rating: 4.6,
      ratingCount: 35000,
      price: "AED 5",
      hoursText: ["08:30 - 20:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 510, close: 1230 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Al+Fahidi+Fort+Dubai",
      distanceKm: 7.2,
      photoUrl:
        "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Al+Fahidi+Fort+Dubai",
      phone: "+971 4 353 1862",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_jumeirah_beach",
      name: "Jumeirah Beach & Sunset Coastline",
      category: "Beach",
      lat: 25.1412,
      lon: 55.1852,
      address: "Jumeirah Beach Road, Dubai, UAE",
      rating: 4.7,
      ratingCount: 52000,
      price: "Free",
      hoursText: ["Open 24 hours"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Jumeirah+Beach+Dubai",
      distanceKm: 8.5,
      photoUrl:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Jumeirah+Beach+Dubai",
      phone: "+971 600 555559",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_jumeirah_mosque",
      name: "Jumeirah Grand Mosque",
      category: "Temples",
      lat: 25.234,
      lon: 55.2655,
      address: "Jumeirah Beach Rd, Jumeirah 1, Dubai, UAE",
      rating: 4.7,
      ratingCount: 19000,
      price: "AED 35 for tour",
      hoursText: ["10:00 - 20:00 (Open to all faiths)"],
      periods: [0, 1, 2, 3, 4, 6].map((day) => ({ day, open: 600, close: 1200 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Jumeirah+Mosque+Dubai",
      distanceKm: 5.1,
      photoUrl:
        "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Jumeirah+Mosque+Dubai",
      phone: "+971 4 353 6666",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_dubai_mall",
      name: "The Dubai Mall & Underwater Aquarium",
      category: "Shopping",
      lat: 25.1985,
      lon: 55.2796,
      address: "Downtown Dubai, Dubai, UAE",
      rating: 4.8,
      ratingCount: 195000,
      price: "Free entry",
      hoursText: ["10:00 - 00:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1440 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Dubai+Mall",
      distanceKm: 1.8,
      photoUrl:
        "https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/The+Dubai+Mall",
      phone: "+971 800 38224 6255",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_atlantis_hotel",
      name: "Atlantis The Palm 5-Star Resort",
      category: "Hotels",
      lat: 25.1304,
      lon: 55.1171,
      address: "Crescent Rd, The Palm Jumeirah, Dubai, UAE",
      rating: 4.9,
      ratingCount: 68000,
      price: "AED 1600",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Atlantis+The+Palm+Dubai",
      distanceKm: 16.5,
      photoUrl:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Atlantis+The+Palm+Dubai",
      phone: "+971 4 426 2000",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
    {
      id: "ae_aquaventure",
      name: "Aquaventure World Waterpark",
      category: "Amusement",
      lat: 25.133,
      lon: 55.12,
      address: "Atlantis The Palm, Crescent Rd, Dubai, UAE",
      rating: 4.7,
      ratingCount: 54000,
      price: "AED 345",
      hoursText: ["09:45 - 18:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 585, close: 1110 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Aquaventure+Dubai",
      distanceKm: 16.8,
      photoUrl:
        "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Aquaventure+Waterpark+Dubai",
      phone: "+971 4 426 0000",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["dubai"],
    },
  ],

  kodaikanal: [
    {
      id: "kk_kodai_lake",
      name: "Kodaikanal Star Lake Promenade",
      category: "Beach",
      lat: 10.2381,
      lon: 77.4892,
      address: "Lake Road, Kodaikanal, Tamil Nadu",
      rating: 4.7,
      ratingCount: 38000,
      price: "Free",
      hoursText: ["06:00 - 18:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 360, close: 1110 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kodaikanal+Lake",
      distanceKm: 0.8,
      photoUrl:
        "https://images.unsplash.com/photo-1626014303757-6467009419f2?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Kodaikanal+Lake",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_pillar_rocks",
      name: "Pillar Rocks & Guna Caves",
      category: "Heritage",
      lat: 10.21,
      lon: 77.47,
      address: "Pillar Rocks Rd, Kodaikanal, Tamil Nadu",
      rating: 4.6,
      ratingCount: 29000,
      price: "₹10",
      hoursText: ["09:00 - 16:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 990 })),
      wheelchair: false,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Pillar+Rocks+Kodaikanal",
      distanceKm: 5.4,
      photoUrl:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Pillar+Rocks+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_kurinji_temple",
      name: "Kurinji Andavar Murugan Temple",
      category: "Temples",
      lat: 10.252,
      lon: 77.502,
      address: "Kurinji Andavar Temple Rd, Kodaikanal",
      rating: 4.7,
      ratingCount: 14000,
      price: "Free",
      hoursText: ["07:00 - 19:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 420, close: 1140 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kurinji+Andavar+Temple+Kodaikanal",
      distanceKm: 3.2,
      photoUrl:
        "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Kurinji+Andavar+Temple+Kodaikanal",
      phone: "+91 4542 240465",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_carlton_hotel",
      name: "The Carlton 5-Star Lakeside Heritage Hotel",
      category: "Hotels",
      lat: 10.237,
      lon: 77.491,
      address: "Lake Rd, Kodaikanal, Tamil Nadu",
      rating: 4.8,
      ratingCount: 7800,
      price: "₹8500",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=The+Carlton+Kodaikanal",
      distanceKm: 0.9,
      photoUrl:
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/The+Carlton+Kodaikanal",
      phone: "+91 4542 248555",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_coakers_walk",
      name: "Coaker's Walk Panoramic Pedestrian Trail",
      category: "Heritage",
      lat: 10.2312,
      lon: 77.4954,
      address: "Coaker's Walk, Kodaikanal, Tamil Nadu 624101",
      rating: 4.6,
      ratingCount: 26000,
      price: "₹30",
      hoursText: ["07:00 - 19:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 420, close: 1140 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Coakers+Walk+Kodaikanal",
      distanceKm: 1.2,
      photoUrl:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Coakers+Walk+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_bryant_park",
      name: "Bryant Park Botanical Conservatory & Rose Garden",
      category: "Culture",
      lat: 10.2335,
      lon: 77.4958,
      address: "Lower Shola Rd, Kodaikanal, Tamil Nadu 624101",
      rating: 4.5,
      ratingCount: 31000,
      price: "₹30",
      hoursText: ["09:00 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1080 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Bryant+Park+Kodaikanal",
      distanceKm: 1.1,
      photoUrl:
        "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Bryant+Park+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_silver_cascade",
      name: "Silver Cascade Waterfalls",
      category: "Heritage",
      lat: 10.2586,
      lon: 77.5186,
      address: "Kodaikanal Ghat Road, Tamil Nadu 624101",
      rating: 4.4,
      ratingCount: 22000,
      price: "Free",
      hoursText: ["Open 24 hours"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Silver+Cascade+Falls+Kodaikanal",
      distanceKm: 6.8,
      photoUrl:
        "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Silver+Cascade+Falls+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_dolphins_nose",
      name: "Dolphin's Nose Cliff Point",
      category: "Fort",
      lat: 10.2035,
      lon: 77.5188,
      address: "Vattakanal, Kodaikanal, Tamil Nadu",
      rating: 4.7,
      ratingCount: 19000,
      price: "Free",
      hoursText: ["06:00 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 360, close: 1080 })),
      wheelchair: false,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Dolphins+Nose+Kodaikanal",
      distanceKm: 8.2,
      photoUrl:
        "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Dolphins+Nose+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_cloud_street",
      name: "Cloud Street Woodfired Bakery & Cafe",
      category: "Food",
      lat: 10.2345,
      lon: 77.4912,
      address: "1 Sunset View, PT Road, Kodaikanal",
      rating: 4.6,
      ratingCount: 8400,
      price: "₹350",
      hoursText: ["09:00 - 21:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1290 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Cloud+Street+Kodaikanal",
      distanceKm: 0.6,
      photoUrl:
        "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Cloud+Street+Kodaikanal",
      phone: "+91 4542 240475",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_astoria_veg",
      name: "Astoria Pure Vegetarian South Indian Restaurant",
      category: "Food",
      lat: 10.2355,
      lon: 77.493,
      address: "Anna Salai, Kodaikanal, Tamil Nadu",
      rating: 4.4,
      ratingCount: 12500,
      price: "₹180",
      hoursText: ["07:00 - 22:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 420, close: 1350 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Astoria+Veg+Kodaikanal",
      distanceKm: 0.4,
      photoUrl:
        "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Astoria+Kodaikanal",
      phone: "+91 4542 245245",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_tibetan_market",
      name: "Tibetan Flea Market & Woolen Bazaar",
      category: "Shopping",
      lat: 10.236,
      lon: 77.494,
      address: "Near Lake Road, Kodaikanal, Tamil Nadu",
      rating: 4.4,
      ratingCount: 15000,
      price: "Free entry",
      hoursText: ["10:00 - 20:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1230 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tibetan+Market+Kodaikanal",
      distanceKm: 0.5,
      photoUrl:
        "https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Tibetan+Market+Kodaikanal",
      phone: "+91 4542 241675",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_danish_display",
      name: "Danish Display Crafts & Homemade Chocolates",
      category: "Shopping",
      lat: 10.2338,
      lon: 77.492,
      address: "Bazaar Road, Kodaikanal, Tamil Nadu",
      rating: 4.5,
      ratingCount: 7200,
      price: "Free entry",
      hoursText: ["09:30 - 21:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 570, close: 1260 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Danish+Display+Kodaikanal",
      distanceKm: 0.7,
      photoUrl:
        "https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Danish+Display+Kodaikanal",
      phone: "+91 4542 240256",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_solar_observatory",
      name: "Kodaikanal Solar Observatory & Science Centre",
      category: "Amusement",
      lat: 10.2325,
      lon: 77.465,
      address: "Observatory Rd, Kodaikanal, Tamil Nadu",
      rating: 4.5,
      ratingCount: 9600,
      price: "₹20",
      hoursText: ["10:00 - 12:00, 14:00 - 16:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 960 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Solar+Observatory+Kodaikanal",
      distanceKm: 4.1,
      photoUrl:
        "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Solar+Observatory+Kodaikanal",
      phone: "+91 4542 240588",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
    {
      id: "kk_sterling_resort",
      name: "Sterling Kodai Lake Luxury Hill Resort",
      category: "Hotels",
      lat: 10.231,
      lon: 77.485,
      address: "Gymkhana Road, Near Lake, Kodaikanal",
      rating: 4.6,
      ratingCount: 6500,
      price: "₹5800",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Sterling+Kodai+Lake",
      distanceKm: 1.6,
      photoUrl:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Sterling+Kodai+Lake",
      phone: "+91 4542 240600",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["kodaikanal"],
    },
  ],

  bihar: [
    {
      id: "bh_mahabodhi_temple",
      name: "Mahabodhi Temple Complex (UNESCO World Heritage Site)",
      category: "Heritage",
      lat: 24.696,
      lon: 84.9913,
      address: "Bodh Gaya, Bihar 824231",
      rating: 4.9,
      ratingCount: 42000,
      price: "Free entry",
      hoursText: ["05:00 - 21:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 300, close: 1260 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Mahabodhi+Temple+Bodh+Gaya",
      distanceKm: 0.5,
      photoUrl:
        "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Mahabodhi+Temple+Bodh+Gaya",
      phone: "+91 631 220 0735",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_nalanda_ruins",
      name: "Ancient Nalanda Mahavihara University Ruins (UNESCO)",
      category: "Heritage",
      lat: 25.1357,
      lon: 85.445,
      address: "Nalanda, Bargaon, Bihar 803111",
      rating: 4.8,
      ratingCount: 31000,
      price: "₹40",
      hoursText: ["09:00 - 17:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1050 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Nalanda+University+Ruins",
      distanceKm: 1.2,
      photoUrl:
        "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Nalanda+University+Ruins",
      phone: "+91 6112 281858",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_patna_sahib",
      name: "Takht Sri Harmandir Ji Patna Sahib Gurudwara",
      category: "Temples",
      lat: 25.5941,
      lon: 85.2281,
      address: "Harmandir Gali, Patna Sahib, Patna, Bihar 800008",
      rating: 4.9,
      ratingCount: 38000,
      price: "Free entry",
      hoursText: ["Open 24 hours"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Takht+Sri+Patna+Sahib",
      distanceKm: 5.6,
      photoUrl:
        "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Takht+Sri+Patna+Sahib",
      phone: "+91 612 264 1821",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_golghar",
      name: "Historic Golghar Granary & Gandhi Maidan",
      category: "Fort",
      lat: 25.6177,
      lon: 85.1439,
      address: "Near Gandhi Maidan, Patna, Bihar 800001",
      rating: 4.5,
      ratingCount: 28000,
      price: "₹20",
      hoursText: ["09:30 - 18:00"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 570, close: 1080 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Golghar+Patna",
      distanceKm: 1.8,
      photoUrl:
        "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Golghar+Patna",
      phone: "+91 612 2506048",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_bihar_museum",
      name: "Bihar World-Class Museum & Heritage Gallery",
      category: "Culture",
      lat: 25.6108,
      lon: 85.1154,
      address: "Bailey Road, Patna, Bihar 800001",
      rating: 4.8,
      ratingCount: 24000,
      price: "₹100",
      hoursText: ["10:00 - 17:00 (Closed Mondays)"],
      periods: [0, 2, 3, 4, 5, 6].map((day) => ({ day, open: 600, close: 1020 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Bihar+Museum+Patna",
      distanceKm: 2.4,
      photoUrl:
        "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Bihar+Museum+Patna",
      phone: "+91 612 223 5731",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_rajgir_glass_bridge",
      name: "Rajgir Glass Bridge & Nature Safari Zoo",
      category: "Amusement",
      lat: 25.015,
      lon: 85.419,
      address: "Nature Safari, Rajgir, Nalanda, Bihar 803116",
      rating: 4.8,
      ratingCount: 19000,
      price: "₹250",
      hoursText: ["09:00 - 17:00 (Closed Mondays)"],
      periods: [0, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1020 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Rajgir+Glass+Bridge",
      distanceKm: 3.5,
      photoUrl:
        "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Rajgir+Glass+Bridge",
      phone: "+91 612 2506048",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_marine_drive",
      name: "Patna Marine Drive Ganga Riverfront Promenade",
      category: "Beach",
      lat: 25.626,
      lon: 85.14,
      address: "Loknayak Ganga Path, Patna, Bihar",
      rating: 4.7,
      ratingCount: 27000,
      price: "Free entry",
      hoursText: ["Open 24 hours"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Patna+Marine+Drive+Ganga+Path",
      distanceKm: 2.1,
      photoUrl:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Patna+Marine+Drive",
      phone: "+91 612 2506048",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_bansi_vihar",
      name: "Bansi Vihar Authentic Bihari Litti Chokha & Thali",
      category: "Food",
      lat: 25.611,
      lon: 85.138,
      address: "Fraser Road, Near Dak Bungalow, Patna, Bihar",
      rating: 4.5,
      ratingCount: 16000,
      price: "₹220",
      hoursText: ["08:00 - 22:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 480, close: 1350 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Bansi+Vihar+Patna",
      distanceKm: 1.0,
      photoUrl:
        "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Bansi+Vihar+Patna",
      phone: "+91 612 222 3447",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_khadi_mall",
      name: "Khadi Mall Patna (World's Largest Khadi & Craft Emporium)",
      category: "Shopping",
      lat: 25.616,
      lon: 85.142,
      address: "East Gandhi Maidan, Patna, Bihar 800001",
      rating: 4.7,
      ratingCount: 18000,
      price: "Free entry",
      hoursText: ["10:30 - 20:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 630, close: 1230 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Khadi+Mall+Patna",
      distanceKm: 1.5,
      photoUrl:
        "https://images.unsplash.com/photo-1520939817895-060bdef4dc1b?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Khadi+Mall+Patna",
      phone: "+91 612 221 9540",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
    {
      id: "bh_hotel_maurya",
      name: "Hotel Maurya 5-Star Luxury Heritage Hotel",
      category: "Hotels",
      lat: 25.6175,
      lon: 85.144,
      address: "Frazer Road, South Gandhi Maidan, Patna, Bihar 800001",
      rating: 4.6,
      ratingCount: 14000,
      price: "₹6500",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Maurya+Patna",
      distanceKm: 1.6,
      photoUrl:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Hotel+Maurya+Patna",
      phone: "+91 612 220 3040",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["bihar"],
    },
  ],

  madurai: [
    {
      id: "md_meenakshi_temple",
      name: "Arulmigu Meenakshi Sundareswarar Temple",
      category: "Temples",
      lat: 9.9195,
      lon: 78.1194,
      address: "Madurai Main, Madurai, Tamil Nadu 625001",
      rating: 4.9,
      ratingCount: 98000,
      price: "Free entry / ₹50 special darshan",
      hoursText: ["05:00 - 12:30, 16:00 - 21:30"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 300, close: 1290 })),
      wheelchair: true,
      outdoor: false,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Meenakshi+Amman+Temple+Madurai",
      distanceKm: 0.5,
      photoUrl:
        "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Meenakshi+Amman+Temple+Madurai",
      phone: "+91 452 234 4360",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["madurai"],
    },
    {
      id: "md_thirumalai_mahal",
      name: "Thirumalai Nayakkar Palace & Fortress",
      category: "Fort",
      lat: 9.9149,
      lon: 78.1245,
      address: "Panthadi, Madurai, Tamil Nadu 625001",
      rating: 4.6,
      ratingCount: 34000,
      price: "₹10",
      hoursText: ["09:00 - 17:00 (Light & sound show 18:45)"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 540, close: 1020 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Thirumalai+Nayakkar+Mahal+Madurai",
      distanceKm: 1.4,
      photoUrl:
        "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Thirumalai+Nayakkar+Palace+Madurai",
      phone: "+91 452 233 2945",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["madurai"],
    },
    {
      id: "md_heritage_hotel",
      name: "Heritage Madurai Luxury Resort",
      category: "Hotels",
      lat: 9.936,
      lon: 78.098,
      address: "11 Kochadai, Melakkal Main Rd, Madurai",
      rating: 4.7,
      ratingCount: 11000,
      price: "₹6500",
      hoursText: ["Open 24/7"],
      periods: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: 0, close: 1440 })),
      wheelchair: true,
      outdoor: true,
      source: "google",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Heritage+Madurai",
      distanceKm: 3.8,
      photoUrl:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      preview3dUrl: "https://earth.google.com/web/search/Heritage+Madurai",
      phone: "+91 452 238 5455",
      tourGuideContact: WORLDWIDE_TOUR_GUIDES["madurai"],
    },
  ],
};

export function getDestKey(name: string): string {
  const n = name.toLowerCase();
  if (
    n.includes("bihar") ||
    n.includes("patna") ||
    n.includes("bodh") ||
    n.includes("gaya") ||
    n.includes("nalanda") ||
    n.includes("rajgir") ||
    n.includes("vaishali")
  )
    return "bihar";
  if (n.includes("kodai")) return "kodaikanal";
  if (n.includes("madurai")) return "madurai";
  if (n.includes("chennai") || n.includes("madras")) return "chennai";
  if (n.includes("maldiv") || n.includes("male") || n.includes("hulhu")) return "maldives";
  if (n.includes("pari") || n.includes("france")) return "paris";
  if (n.includes("london") || n.includes("uk") || n.includes("britain")) return "london";
  if (n.includes("dubai") || n.includes("uae") || n.includes("emirates")) return "dubai";
  if (n.includes("tokyo") || n.includes("japan")) return "tokyo";
  if (n.includes("rome") || n.includes("roma") || n.includes("italy")) return "rome";
  if (n.includes("york") || n.includes("nyc") || n.includes("manhattan")) return "newyork";
  if (n.includes("bali") || n.includes("indonesia") || n.includes("ubud")) return "bali";
  return "general";
}

export function enrichPlace(p: Place, centre: { lat: number; lon: number; name: string }): Place {
  const destKey = getDestKey(centre.name);
  const guide = WORLDWIDE_TOUR_GUIDES[destKey] ?? WORLDWIDE_TOUR_GUIDES["general"]!;

  // User rule: Each place's photo must be the actual photo of that place. Never show a wrong image
  // (for example an Eiffel Tower photo for a Chennai temple or Kodaikanal viewpoint).
  // If no authentic real photo is verified for this place, keep photoUrl as null so a clean placeholder is shown.
  const photo = p.photoUrl || null;

  const preview3d =
    p.preview3dUrl ||
    `https://earth.google.com/web/search/${encodeURIComponent(p.name + " " + centre.name)}`;

  return {
    ...p,
    distanceKm: p.distanceKm
      ? Math.round(p.distanceKm * 10) / 10
      : Math.round(haversineKm(centre, { lat: p.lat, lon: p.lon }) * 10) / 10,
    photoUrl: photo,
    preview3dUrl: preview3d,
    phone: p.phone || guide.phone,
    tourGuideContact: p.tourGuideContact || guide,
  };
}
