// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  const LOCAL_AUTH_KEY = "rootify_auth_user";
  const listeners = new Set<(event: string, session: any) => void>();

  function getUser(): any {
    if (typeof window === "undefined") return null;
    try {
      const data = localStorage.getItem(LOCAL_AUTH_KEY);
      if (data) return JSON.parse(data);
    } catch {
      // ignore
    }
    return {
      id: "guest-user",
      email: "traveller@rootify.com",
      user_metadata: { display_name: "Traveller" },
    };
  }

  function getSession(): any {
    const user = getUser();
    if (!user) return null;
    return {
      access_token: "mock-access-token",
      token_type: "bearer",
      user,
    };
  }

  function notifyAuth(event: string) {
    const s = getSession();
    listeners.forEach((cb) => {
      try {
        cb(event, s);
      } catch {
        // ignore
      }
    });
  }

  return {
    auth: {
      async getUser() {
        const user = getUser();
        return { data: { user }, error: null };
      },
      async getSession() {
        const session = getSession();
        return { data: { session }, error: null };
      },
      async signInWithPassword({ email }: any) {
        const user = {
          id: `u_${Date.now()}`,
          email,
          user_metadata: { display_name: email.split("@")[0] || "Traveller" },
        };
        if (typeof window !== "undefined") {
          localStorage.setItem(LOCAL_AUTH_KEY, JSON.stringify(user));
        }
        notifyAuth("SIGNED_IN");
        return { data: { user, session: getSession() }, error: null };
      },
      async signUp({ email, options }: any) {
        const user = {
          id: `u_${Date.now()}`,
          email,
          user_metadata: {
            display_name: options?.data?.display_name || email.split("@")[0] || "Traveller",
          },
        };
        if (typeof window !== "undefined") {
          localStorage.setItem(LOCAL_AUTH_KEY, JSON.stringify(user));
        }
        notifyAuth("SIGNED_IN");
        return { data: { user, session: getSession() }, error: null };
      },
      async signOut() {
        if (typeof window !== "undefined") {
          localStorage.removeItem(LOCAL_AUTH_KEY);
        }
        notifyAuth("SIGNED_OUT");
        return { error: null };
      },
      onAuthStateChange(cb: (event: string, session: any) => void) {
        listeners.add(cb);
        const timerId = setTimeout(() => cb("INITIAL_SESSION", getSession()), 0);
        return {
          data: {
            subscription: {
              unsubscribe: () => {
                listeners.delete(cb);
                clearTimeout(timerId);
              },
            },
          },
        };
      },
    },
    from(table: string) {
      const getRows = (): any[] => {
        if (typeof window === "undefined") return [];
        try {
          const raw = localStorage.getItem(`mock_db_${table}`);
          return raw ? JSON.parse(raw) : [];
        } catch {
          return [];
        }
      };
      const saveRows = (rows: any[]) => {
        if (typeof window === "undefined") return;
        try {
          localStorage.setItem(`mock_db_${table}`, JSON.stringify(rows));
        } catch {
          // ignore
        }
      };

      const builder: any = {
        filters: [] as ((r: any) => boolean)[],
        sortFn: null as ((a: any, b: any) => number) | null,
        select() {
          return this;
        },
        order(col: string, { ascending = true }: any = {}) {
          this.sortFn = (a: any, b: any) => {
            const va = a[col];
            const vb = b[col];
            if (va < vb) return ascending ? -1 : 1;
            if (va > vb) return ascending ? 1 : -1;
            return 0;
          };
          return this;
        },
        eq(col: string, val: any) {
          this.filters.push((r: any) => r[col] === val);
          return this;
        },
        async then(resolve: any, reject: any) {
          try {
            let data = getRows();
            for (const f of this.filters) data = data.filter(f);
            if (this.sortFn) data.sort(this.sortFn);
            resolve({ data, error: null });
          } catch (e) {
            if (reject) {
              reject(e);
            } else {
              resolve({ data: [], error: e });
            }
          }
        },
        single() {
          return {
            then: async (resolve: any, reject: any) => {
              try {
                let data = getRows();
                for (const f of this.filters) data = data.filter(f);
                resolve({ data: data[0] ?? null, error: data[0] ? null : new Error("Not found") });
              } catch (e) {
                if (reject) {
                  reject(e);
                } else {
                  resolve({ data: null, error: e });
                }
              }
            },
          };
        },
        maybeSingle() {
          return {
            then: async (resolve: any, reject: any) => {
              try {
                let data = getRows();
                for (const f of this.filters) data = data.filter(f);
                resolve({ data: data[0] ?? null, error: null });
              } catch (e) {
                if (reject) {
                  reject(e);
                } else {
                  resolve({ data: null, error: e });
                }
              }
            },
          };
        },
        insert(records: any) {
          const arr = Array.isArray(records) ? records : [records];
          const rows = getRows();
          const inserted = arr.map((r: any) => ({
            id: r.id || `trip_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            ...r,
          }));
          rows.push(...inserted);
          saveRows(rows);
          return {
            select() {
              return {
                single: async () => ({ data: inserted[0], error: null }),
                then: async (resolve: any) => resolve({ data: inserted, error: null }),
              };
            },
            then: async (resolve: any) => resolve({ data: inserted, error: null }),
          };
        },
        update(updates: any) {
          return {
            eq: (col: string, val: any) => {
              const rows = getRows();
              let updatedItem: any = null;
              const next = rows.map((r: any) => {
                if (r[col] === val) {
                  updatedItem = { ...r, ...updates, updated_at: new Date().toISOString() };
                  return updatedItem;
                }
                return r;
              });
              saveRows(next);
              return {
                select() {
                  return {
                    single: async () => ({ data: updatedItem, error: null }),
                  };
                },
                then: async (resolve: any) => resolve({ data: updatedItem, error: null }),
              };
            },
          };
        },
        delete() {
          return {
            eq: (col: string, val: any) => {
              const rows = getRows();
              const next = rows.filter((r: any) => r[col] !== val);
              saveRows(next);
              return Promise.resolve({ data: null, error: null });
            },
          };
        },
      };
      return builder;
    },
  };
}

const CLIENT_LOCAL_AUTH_KEY = "rootify_auth_user";
const CLIENT_AUTH_LISTENERS = new Set<(event: string, session: any) => void>();

function generateClientUuid(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

function getClientStoredUser(): any {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(CLIENT_LOCAL_AUTH_KEY);
    if (raw) {
      const u = JSON.parse(raw);
      if (u && typeof u === "object") return u;
    }
    const name = localStorage.getItem("rootify_entered_name");
    const email = localStorage.getItem("rootify_entered_email");
    if (name || email) {
      let id = localStorage.getItem("rootify_user_uuid");
      if (!id || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
        id = generateClientUuid();
        localStorage.setItem("rootify_user_uuid", id);
      }
      const synthetic = {
        id,
        email: email || "traveller@rootify.com",
        name: name || "Traveller",
        user_metadata: { display_name: name || "Traveller" },
        created_at: new Date().toISOString(),
      };
      localStorage.setItem(CLIENT_LOCAL_AUTH_KEY, JSON.stringify(synthetic));
      return synthetic;
    }
  } catch {
    // ignore
  }
  return null;
}

function clientToSupabaseUser(local: any): any {
  if (!local) return null;
  const id =
    local.id && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(local.id)
      ? local.id
      : generateClientUuid();
  return {
    id,
    email: local.email || "traveller@rootify.com",
    aud: "authenticated",
    role: "authenticated",
    user_metadata: {
      display_name: local.user_metadata?.display_name || local.name || "Traveller",
    },
    app_metadata: { provider: "email" },
    created_at: local.created_at || new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
}

function clientToSupabaseSession(user: any): any {
  if (!user) return null;
  return {
    access_token: `rootify-access-${user.id}`,
    refresh_token: `rootify-refresh-${user.id}`,
    token_type: "bearer",
    expires_in: 3600,
    expires_at: Math.floor(Date.now() / 1000) + 3600,
    user,
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  const authWrapper = new Proxy(realClient.auth, {
    get(target, prop, receiver) {
      if (prop === "getUser") {
        return async (...args: any[]) => {
          try {
            const res = await target.getUser(...args);
            if (res.data?.user) return res;
          } catch {
            // fall through
          }
          const local = getClientStoredUser();
          if (local) {
            return { data: { user: clientToSupabaseUser(local) }, error: null };
          }
          return { data: { user: null }, error: new Error("No user found") };
        };
      }

      if (prop === "getSession") {
        return async () => {
          try {
            const res = await target.getSession();
            if (res.data?.session) return res;
          } catch {
            // fall through
          }
          const local = getClientStoredUser();
          if (local) {
            const user = clientToSupabaseUser(local);
            return { data: { session: clientToSupabaseSession(user) }, error: null };
          }
          return { data: { session: null }, error: null };
        };
      }

      if (prop === "signUp") {
        return async (creds: any) => {
          const email = creds?.email || "traveller@rootify.com";
          const displayName =
            creds?.options?.data?.display_name || email.split("@")[0] || "Traveller";
          const id = generateClientUuid();
          const localUser = {
            id,
            email,
            name: displayName,
            user_metadata: { display_name: displayName },
            created_at: new Date().toISOString(),
          };
          if (typeof window !== "undefined") {
            localStorage.setItem(CLIENT_LOCAL_AUTH_KEY, JSON.stringify(localUser));
            localStorage.setItem("rootify_entered_name", displayName);
            localStorage.setItem("rootify_entered_email", email);
            localStorage.setItem("rootify_user_uuid", id);
          }
          const user = clientToSupabaseUser(localUser);
          const session = clientToSupabaseSession(user);

          try {
            await target.signUp(creds);
          } catch {
            // ignore backend signup errors
          }

          CLIENT_AUTH_LISTENERS.forEach((cb) => {
            try {
              cb("SIGNED_IN", session);
            } catch {
              // ignore
            }
          });

          return { data: { user, session }, error: null };
        };
      }

      if (prop === "signInWithPassword") {
        return async (creds: any) => {
          try {
            const res = await target.signInWithPassword(creds);
            if (res.data?.session) return res;
          } catch {
            // fall through
          }
          const email = creds?.email || "traveller@rootify.com";
          const displayName = email.split("@")[0] || "Traveller";
          const id = generateClientUuid();
          const localUser = {
            id,
            email,
            name: displayName,
            user_metadata: { display_name: displayName },
            created_at: new Date().toISOString(),
          };
          if (typeof window !== "undefined") {
            localStorage.setItem(CLIENT_LOCAL_AUTH_KEY, JSON.stringify(localUser));
            localStorage.setItem("rootify_entered_name", displayName);
            localStorage.setItem("rootify_entered_email", email);
            localStorage.setItem("rootify_user_uuid", id);
          }
          const user = clientToSupabaseUser(localUser);
          const session = clientToSupabaseSession(user);
          CLIENT_AUTH_LISTENERS.forEach((cb) => {
            try {
              cb("SIGNED_IN", session);
            } catch {
              // ignore
            }
          });
          return { data: { user, session }, error: null };
        };
      }

      if (prop === "signOut") {
        return async (...args: any[]) => {
          try {
            await target.signOut(...args);
          } catch {
            // ignore
          }
          if (typeof window !== "undefined") {
            localStorage.removeItem(CLIENT_LOCAL_AUTH_KEY);
            localStorage.removeItem("rootify_entered_name");
            localStorage.removeItem("rootify_entered_email");
          }
          CLIENT_AUTH_LISTENERS.forEach((cb) => {
            try {
              cb("SIGNED_OUT", null);
            } catch {
              // ignore
            }
          });
          return { error: null };
        };
      }

      if (prop === "onAuthStateChange") {
        return (cb: (event: string, session: any) => void) => {
          CLIENT_AUTH_LISTENERS.add(cb);
          const sub = target.onAuthStateChange((evt, s) => {
            if (s) {
              cb(evt, s);
            } else {
              const local = getClientStoredUser();
              if (local) {
                const user = clientToSupabaseUser(local);
                cb("SIGNED_IN", clientToSupabaseSession(user));
              } else {
                cb(evt, null);
              }
            }
          });

          const timerId = setTimeout(() => {
            const local = getClientStoredUser();
            if (local) {
              const user = clientToSupabaseUser(local);
              cb("INITIAL_SESSION", clientToSupabaseSession(user));
            }
          }, 0);

          return {
            data: {
              subscription: {
                unsubscribe: () => {
                  CLIENT_AUTH_LISTENERS.delete(cb);
                  clearTimeout(timerId);
                  try {
                    sub?.data?.subscription?.unsubscribe();
                  } catch {
                    // ignore
                  }
                },
              },
            },
          };
        };
      }

      return Reflect.get(target, prop, receiver);
    },
  });

  return new Proxy(realClient, {
    get(target, prop, receiver) {
      if (prop === "auth") return authWrapper;
      return Reflect.get(target, prop, receiver);
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
